// Generated by gencpp from file toi_bot_stt/speechTT.msg
// DO NOT EDIT!


#ifndef TOI_BOT_STT_MESSAGE_SPEECHTT_H
#define TOI_BOT_STT_MESSAGE_SPEECHTT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace toi_bot_stt
{
template <class ContainerAllocator>
struct speechTT_
{
  typedef speechTT_<ContainerAllocator> Type;

  speechTT_()
    : query()
    , response()
    , intent()  {
    }
  speechTT_(const ContainerAllocator& _alloc)
    : query(_alloc)
    , response(_alloc)
    , intent(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _query_type;
  _query_type query;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _intent_type;
  _intent_type intent;





  typedef boost::shared_ptr< ::toi_bot_stt::speechTT_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::toi_bot_stt::speechTT_<ContainerAllocator> const> ConstPtr;

}; // struct speechTT_

typedef ::toi_bot_stt::speechTT_<std::allocator<void> > speechTT;

typedef boost::shared_ptr< ::toi_bot_stt::speechTT > speechTTPtr;
typedef boost::shared_ptr< ::toi_bot_stt::speechTT const> speechTTConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::toi_bot_stt::speechTT_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::toi_bot_stt::speechTT_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace toi_bot_stt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'toi_bot_stt': ['/home/intel/toibot_ws/src/ToiBot1/src/toi_bot_stt/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::toi_bot_stt::speechTT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::toi_bot_stt::speechTT_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::toi_bot_stt::speechTT_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::toi_bot_stt::speechTT_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::toi_bot_stt::speechTT_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::toi_bot_stt::speechTT_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::toi_bot_stt::speechTT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2e0321a6d60d7971f3d93f2eaf3408e";
  }

  static const char* value(const ::toi_bot_stt::speechTT_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2e0321a6d60d797ULL;
  static const uint64_t static_value2 = 0x1f3d93f2eaf3408eULL;
};

template<class ContainerAllocator>
struct DataType< ::toi_bot_stt::speechTT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "toi_bot_stt/speechTT";
  }

  static const char* value(const ::toi_bot_stt::speechTT_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::toi_bot_stt::speechTT_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string query\n\
string response\n\
string intent\n\
";
  }

  static const char* value(const ::toi_bot_stt::speechTT_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::toi_bot_stt::speechTT_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.query);
      stream.next(m.response);
      stream.next(m.intent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speechTT_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::toi_bot_stt::speechTT_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::toi_bot_stt::speechTT_<ContainerAllocator>& v)
  {
    s << indent << "query: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.query);
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
    s << indent << "intent: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.intent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOI_BOT_STT_MESSAGE_SPEECHTT_H
